### ISSUE TITLE
winで実行すると文字コードで怒られる

### ISSUE THREAD

**Issue by uwi** [Saqoosha/wonderfl-archive#4]
win, Python3.5で実行するとget_userのファイルに書き込むところで次のように怒られます。
Python3ではopenの'w'を'wb'にしてf.write(raw.encode('utf-8'))とするとうまくいくのですが、Python2だとどういう書き方でうまくいくのか検証できないです。

```
Traceback (most recent call last):
  File "C:/develop/wonderfl-archive/scrape.py", line 114, in get_user
    f.write(raw)
UnicodeEncodeError: 'cp932' codec can't encode character '\xa9' in position 847: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/develop/wonderfl-archive/scrape.py", line 157, in <module>
    code_pages = get_user('uwi')
  File "C:/develop/wonderfl-archive/scrape.py", line 116, in get_user
    f.write(raw.encode('utf-8'))
TypeError: write() argument must be str, not bytes
```

**Comment by Saqoosha** [comment]
http://toriaezu-engineer.hatenablog.com/entry/2016/08/25/224447
これかな？

**Comment by uwi** [comment]
書き込むときなのでそれではないです。といってももうwonderfl閉じちゃいましたが…
